apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asp-net-app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: asp-net-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  minReadySeconds: 5 #Wait this many seconds before putting into service
  template:
    metadata:
      labels:
        service: asp-net-service
    spec:
      containers:
      - name: asp-net-app
        image: jzaccone/asp-net-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: asp-net-service
  labels:
    app: asp-net-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    service: asp-net-service
