apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asp-net-app-secret
spec:
  replicas: 3
  selector:
    matchLabels:
      service: asp-net-service-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  minReadySeconds: 5 #Wait this many seconds before putting into service
  template:
    metadata:
      labels:
        service: asp-net-service-secret
    spec:
      containers:
      - name: asp-net-app-secret
        image: jzaccone/asp-net-app
        ports:
        - containerPort: 80
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: supersecret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: supersecret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: asp-net-service-secret
  labels:
    app: asp-net-service-secret
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30081
  selector:
    service: asp-net-service-secret
